services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: cmzl2025
      MYSQL_DATABASE: api_car_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    environment:
      DB_NAME: api_car_db
      DB_USER: root
      DB_PASSWORD: cmzl2025
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
    command: ./start.sh

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 3000

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge