version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: api_car_db
      MYSQL_ROOT_PASSWORD: cmzl2025
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django-app
    command: ["sh", "/app/execute-migrations.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=api_car_db
      - DB_USER=root
      - DB_PASSWORD=cmzl2025
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  mysql_data:
