# Generated by Django 5.2.1 on 2025-06-17 02:57

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('status', django_mysql.models.EnumField(choices=[('DISPONIVEL', 'DISPONÍVEL'), ('ALUGADO', 'ALUGADO'), ('EM_MANUTENCAO', 'EM MANUTENÇÃO'), ('RESERVADO', 'RESERVADO'), ('INDISPONIVEL', 'INDISPONÍVEL'), ('FORA_DE_CIRCULACAO', 'FORA DE CIRCULAÇÃO')], default='DISPONIVEL')),
            ],
        ),
    ]
